version: '3.7'
services:
  api:
    container_name: assignment_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/app/
    entrypoint: /start-reload.sh